services:
  redis-stack-1:
    image: redis/redis-stack:latest
    container_name: redis-stack-1
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-stack-1/data:/data
    networks:
      - redis-cluster-net
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-stack-2:
    image: redis/redis-stack:latest
    container_name: redis-stack-2
    ports:
      - "6380:6379"
      - "8002:8001"
    volumes:
      - ./redis-stack-2/data:/data
    networks:
      - redis-cluster-net
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-stack-3:
    image: redis/redis-stack:latest
    container_name: redis-stack-3
    ports:
      - "6381:6379"
      - "8003:8001"
    volumes:
      - ./redis-stack-3/data:/data
    networks:
      - redis-cluster-net
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-stack-4:
    image: redis/redis-stack:latest
    container_name: redis-stack-4
    ports:
      - "6382:6379"
      - "8004:8001"
    volumes:
      - ./redis-stack-4/data:/data
    networks:
      - redis-cluster-net
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-stack-5:
    image: redis/redis-stack:latest
    container_name: redis-stack-5
    ports:
      - "6383:6379"
      - "8005:8001"
    volumes:
      - ./redis-stack-5/data:/data
    networks:
      - redis-cluster-net
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-stack-6:
    image: redis/redis-stack:latest
    container_name: redis-stack-6
    ports:
      - "6384:6379"
      - "8006:8001"
    volumes:
      - ./redis-stack-6/data:/data
    networks:
      - redis-cluster-net
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

networks:
  redis-cluster-net:
    external: false